### ISSUE TITLE
Portal does not respond to API 

### ISSUE THREAD

**Issue by ghost** [PaloAltoNetworks/aws#10]
Hello Narayan
I have been doing some tests with PANOS 8.0, but for some reasons lambda is failing to update the portal with gateway address. When I looked at the logs at cloudwatch, I can see the Portal is not responding to api calls:

23:15:41
[INFO]	2017-05-31T23:15:41.36Z	c8af41c8-4656-11e7-9ee6-171ce05b1d29	[INFO]: No response from FW. So maybe not up!
23:15:41
[INFO]	2017-05-31T23:15:41.36Z	c8af41c8-4656-11e7-9ee6-171ce05b1d29	[INFO] FW is not up...yet
23:15:41
[INFO]	2017-05-31T23:15:41.36Z	c8af41c8-4656-11e7-9ee6-171ce05b1d29	[INFO]: 2 or more minutes left in lambda function. So will check again in 30s
23:16:11
[INFO]	2017-05-31T23:16:11.59Z	c8af41c8-4656-11e7-9ee6-171ce05b1d29	[INFO]: Sending command: https://52.53.60.56/api/?type=op&cmd=<show><jobs><id>1</id></jobs></show>&key=LUFRPT11dEtJM0tPTzVHMnJhelpHUzVDN2k5clpTd0E9TUdXZUpoeG5LOVJXemxuVGZ6VGtKdWNlckU2d2RoK2U2RGRxVU1Oc3VJaz0=
23:16:16
[INFO]	2017-05-31T23:16:16.65Z	c8af41c8-4656-11e7-9ee6-171ce05b1d29	[INFO]: No response from FW. So maybe not up!
23:16:16
[INFO]	2017-05-31T23:16:16.65Z	c8af41c8-4656-11e7-9ee6-171ce05b1d29	[INFO] FW is not up...yet
23:16:16
[INFO]	2017-05-31T23:16:16.65Z	c8af41c8-4656-11e7-9ee6-171ce05b1d29	[INFO]: 2 or more minutes left in lambda function. So will check again in 30s
23:16:46
[INFO]	2017-05-31T23:16:46.95Z	c8af41c8-4656-11e7-9ee6-171ce05b1d29	[INFO]: Sending command: https://52.53.60.56/api/?type=op&cmd=<show><jobs><id>1</id></jobs></show>&key=LUFRPT11dEtJM0tPTzVHMnJhelpHUzVDN2k5clpTd0E9TUdXZUpoeG5LOVJXemxuVGZ6VGtKdWNlckU2d2RoK2U2RGRxVU1Oc3VJaz0=
23:16:51
[INFO]	2017-05-31T23:16:51.101Z	c8af41c8-4656-11e7-9ee6-171ce05b1d29	[INFO]: No response from FW. So maybe not up!
23:16:51
[INFO]	2017-05-31T23:16:51.101Z	c8af41c8-4656-11e7-9ee6-171ce05b1d29	[INFO] FW is not up...yet
23:16:51
[INFO]	2017-05-31T23:16:51.101Z	c8af41c8-4656-11e7-9ee6-171ce05b1d29	[INFO] have less than two minutes so call self

I was not able to find out why the API is failing, but tried to run the same API from my laptop and i got a response:

curl -k -g "https://172.16.1.21/api/?type=op&cmd=<show><jobs><id>1</id></jobs></show>&key=LUFRPT14MW5xOEo1R09KVlBZNnpnemh0VHRBOWl6TGM9bXcwM3JHUGVhRlNiY0dCR0srNERUQT09"
<response status="success"><result><job><tenq>2017/05/31 15:47:27</tenq><tdeq>15:47:27</tdeq><id>1</id><user></user><type>AutoCom</type><status>FIN</status><queued>NO</queued><stoppable>no</stoppable><result>OK</result><tfin>15:47:42</tfin><description></description><positionInQ>0</positionInQ><progress>100</progress><details><line>Configuration committed successfully</line><line>Successfully committed last configuration</line></details><warnings><line>Warning: tunnel tunnel.100 ipv6 is not enabled. IPv6 address will be ingored!</line><line>(Module: rasmgr)</line></warnings></job></result></response>

**Comment by amjadhalim** [comment]
was able to fix the issue by doing the following:
1. The name cloudformation stack must be "gp-asg-demo". This was not mentioned in the pdf file
2. Modified the scripts in config_fw.zip, due to the changes related to GlobalProtect in 8.0, the api has to be updated
