### ISSUE TITLE
Solution - Failed Deployment using GlobalProtect CloudFormation Template

### ISSUE THREAD

**Issue by ghost** [PaloAltoNetworks/aws#13]
Hey there,

The CloudFormation template you currently have posted for GlobalProtect is not up to date. There are three variables that need to change:

All the mappings to EC2 AMIs need to be changed to the proper AMI

Before:
"us-west-2"     : { "AMI": "ami-e4be4b84" },
"eu-west-1"     : { "AMI": "ami-5d92132e"},
"us-east-1"     : { "AMI": "ami-7dcb9906" },
"eu-central-1"     : { "AMI": "ami-8be001e4"},
"ap-northeast-1"   : { "AMI": "ami-b84b5ad6"},
"ap-southeast-1"   : { "AMI": "ami-946da7f7"},
"ap-southeast-2"   : { "AMI": "ami-d7c6e5b4"}

After:
"us-west-2"     : { "AMI": "ami-d28992ab" },
"eu-west-1"     : { "AMI": "ami-0f88a16f"},
"us-east-1"     : { "AMI": "ami-7dcb9906" },
"eu-central-1"     : { "AMI": "ami-0f08b76b"},
"ap-northeast-1"   : { "AMI": "ami-ab04e7cd"},
"ap-southeast-1"   : { "AMI": "ami-1897057b"},
"ap-southeast-2"   : { "AMI": "ami-8ed3cced"}

Instance Type "c" is no longed available for Palo Alto's EC2 instances and has been changed to "m"

Before: "InstanceType" : "c4.xlarge"
After: "InstanceType" : "m4.xlarge"

The volume size will fail at 40gb so I would increase it to 80gb

Before: "VolumeSize" : "40"
After: "VolumeSize" : "80"

I have also listed the updated JSON file within the issue/solution thread.

- Matt Lubbers
[gp-asg.txt](https://github.com/PaloAltoNetworks/aws/files/1580501/gp-asg.txt)

**Comment by narayan-iyengar** [comment]
Thanks Matt.

I will look into updating the template with your changes.
