### ISSUE TITLE
Purpose of panupv2-all-contents-695-4002.

### ISSUE THREAD

**Issue by berridgd** [PaloAltoNetworks/aws#17]
What is the purpose of the panupv2-all-contents-695-4002 file? What does it contain?

**Comment by narayan-iyengar** [comment]
Hi Daniel,
    The contents file contains updated threat signatures. This is very (very very) old and you should not use it. I have not had the chance to clean the repo up.


In the firewall, you can update to the latest content package manually...

**Comment by berridgd** [comment]
Ah, so the bootstrapping will work without the panupv2-all-contents-695-4002 file?

**Comment by narayan-iyengar** [comment]
Probably not...as the firewall will reject an old content most likely.

I'd say just delete the file from your bootstrap folder and manually install new content

**Comment by berridgd** [comment]
How does the instance 'know' to use the files located in s3 bucket for configuration? The only thing in the cft that hints at this is the following lines in the User Data section...

 "UserData": {
                    "Fn::Base64": {
                        "Fn::Join": [
                            "",
                            [
                                "vmseries-bootstrap-aws-s3bucket=",
                                {
                                    "Ref": "BootstrapBucketName"
                                }
                            ]
                        ]
                    }
                }

Is the PA looking for the line 'vmseries-bootstrap-aws-s3bucket' to determine where to retrieve its configuration information from?

**Comment by narayan-iyengar** [comment]
Yes. That is correct.


--
Thanks,
/narayan
________________________________

**Comment by ghostpop** [comment]
Also, in the Parameters section of the cft, there is a section that states that the user will be presented with a field named "BootstrapBucketName". At the time that the stack is run, the user must enter in the name of the bucket that contains the bootstrap.xml file.
If you don't put in a value for the 'BootstrapBucketName' during the run of the stack, it won't know which bucket to look into.

**Comment by berridgd** [comment]
Also, if I want to change the configuration of the Palo Altos after the cft is deployed do I have to redeploy the entire cft or can I upload new configuration files to the S3 bucket and trigger the configuration update in a different fashion?

**Comment by tejaswinisuryaprakash** [comment]
I would suggest you try the "Update" functionality first and see if it supports the change you need.
    On Thursday, 26 July 2018, 11:28:34 AM GMT-7, Daniel Berridge <notifications@github.com> wrote:  
 
 
Also, if I want to change the configuration of the Palo Altos after the cft is deployed do I have to redeploy the entire cft or can I upload new configuration files to the S3 bucket and trigger the configuration update in a different fashion?

**Comment by berridgd** [comment]
Good point, thanx!
